name: SnapShootersPhotography
favicon: null
layout_spectrum: 0.4740346276666969
typography_spectrum: 0.9090271617751569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8890198261942714
  lightness: 0.056538229109719396
  saturation: 0.5492500436957926
  rhythmicContrast: 0.814787924522534
purpose: []
