name: SnapShootersPhotography
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.70732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#727272'
    - '#dddddd'
    - '#afafaf'
    - '#840000'
  brandStrength: 1
  lightness: 0.056538229109719396
  saturation: 0.625
  rhythmicContrast: 0.814787924522534
purpose: []
